### ISSUE TITLE
The pair of (city, countryCode) is not unique

### ISSUE THREAD

**Issue by rexarski** [reorx/jsoncv#1]
Just a thought:

Ideally `(city, region)` would be a better choice as you could easily have multiple locations under the same name like:

```
Arlington, TX
Arlington, VA
```

Both will be shown as `Arlington, US` for now.

Even in Chinese there are tons of examples: [中国有哪些同音不同字的地名？](https://www.zhihu.com/question/28793923/answer/43301082)

Thanks for your time.

**Comment by reorx** [comment]
Yes, this is definitely something I forget to cover. Also, I didn't put `address` and `postalCode` in the line. I think I'm gonna change it to:

```
address. city, region, postalCode, countryCode
```

e.g. `2712 Broadway St. San Francisco, California, CA 94115, US`

what do you think?

**Comment by reorx** [comment]
A preview with `address`:

![image](https://user-images.githubusercontent.com/405972/218645014-91aab565-09b4-4148-8715-cf4ec0869388.png)

without `address`:

![image](https://user-images.githubusercontent.com/405972/218645098-7f59d9fd-e809-40ed-93e7-1b54198205c6.png)

**Comment by rexarski** [comment]
Hi @reorx, thanks for your reply. Been using your previous works for a while (papermodx, obsidian plugin), so it's just a way to show my appreciation ;)

The full address, of course, seems pretty good. However, people usually try to avoid this due to privacy concerns. I feel like `city, region` would be enough (for most cases).

Thanks again and keep up the good work!

**Comment by reorx** [comment]
Then I think 4e2c1f0 is enough to complete this requirement. By unchecking all the other properties you don't want to expose in location, you'll get the `city, region` display as the screenshot shown below:

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/405972/218923587-5cbe3ce9-e004-4d75-8e0b-487a25801a59.png">
